book_recipe/book_recipe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('users.urls')),

]

book_recipe/main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='home'),
    path('favorites/<int:recipe_id>', views.favorite_recipe, name='favorite_recipe'),
    path('favorites/', views.user_favorite, name='user_favorite'),
    path('recipes_launch', views.recipes_launch, name='recipes_launch'),
    path('recept1', views.recept1),
    path('profile1', views.profile1, name='profile1'),
    path('<int:pk>/edit', views.RecipeEdit.as_view(), name='recipe_edit'),
    # path('recipe/<int:recipe_id>/toggle_favorite/', toggle_favorite, name='toggle_favorite'),
    # path('recipe/<int:recipe_id>/add_to_favorites/', views.add_to_favorites, name='add_to_favorites'),
    # path('recipe/<int:recipe_id>/remove_from_favorites/', views.remove_from_favorites, name='remove_from_favorites'),

    # Recipes listed
    path('breakfast', views.breakfast, name='breakfast'),
    path('lunch', views.lunch, name='lunch'),
    path('dinner', views.dinner, name='dinner'),
    path('dessert', views.dessert, name='dessert'),
    path('drink', views.drink, name='drink'),

    # Recipes detailed
    path('breakfast/<int:pk>', views.RecipeId.as_view(), name='breakfast_detail'),
    path('lunch/<int:pk>', views.RecipeId.as_view(), name='lunch_detail'),
    path('dinner/<int:pk>', views.RecipeId.as_view(), name='dinner_detail'),
    path('dessert/<int:pk>', views.RecipeId.as_view(), name='dessert_detail'),
    path('drink/<int:pk>', views.RecipeId.as_view(), name='drink_detail'),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

book_recipe/main/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth import get_user_model


CATEGORY_CHOICES = (
    ('breakfast', 'BREAKFAST'),
    ('lunch', 'LUNCH'),
    ('dinner', 'DINNER'),
    ('dessert', 'DESSERT'),
    ('drink', 'DRINK'),
)


class Recipe(models.Model):
    title = models.CharField('Название блюда', max_length=50)
    image = models.ImageField(upload_to='image/')
    ingredients = models.CharField('Ингредиенты', max_length=300)
    calories = models.IntegerField()
    steps = models.TextField('Шаги приготовления')
    time_cooking = models.IntegerField(default=40)
    rating = models.IntegerField(default=0)
    category = models.CharField(max_length=9, choices=CATEGORY_CHOICES, default='breakfast')
    online = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    favorite = models.ManyToManyField(User, related_name='favorite', blank=True)

    def __str__(self):
        return f'{self.user.username}: {self.category} - "{self.title}"'

    def get_absolute_url(self):
        return f'/{self.category}/{self.id}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)



class Comment(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    text = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['-time']
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    def approve(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.text

book_recipe/main/forms.py
from .models import Recipe, Comment
from django import forms


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'ingredients', 'steps', 'calories', 'category', 'image', 'online']
        widgets = {
            'title': forms.TextInput(attrs={
                "class": 'form-control',
                'placeholder': 'Название блюда'
            }),
            'ingredients': forms.TextInput(attrs={
                "class": 'form-control',
                'placeholder': 'Ингридиенты'
            }),
            'steps': forms.Textarea(attrs={
                "class": 'form-control',
                'placeholder': 'Шаги приготовления'
            }),
            'calories': forms.NumberInput(attrs={
                "class": 'form-control',
                'placeholder': 'Кол-во калорий'
            }),
        }

    def __init__(self, *args, **kwargs):
        super(RecipeForm, self).__init__(*args, **kwargs)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

        labels = {
            'text': 'Ваш комментарий'
        }

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

book_recipe/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import DetailView

from .forms import RecipeForm
from django.views.generic import DetailView, UpdateView
from .models import Recipe


class RecipeEdit(UpdateView):
    model = Recipe
    template_name = 'main/edit.html'
    form_class = RecipeForm


def index(request):
    return render(request, 'main/index.html')


def recipes(request):
    return render(request, 'main/recipes.html')


def breakfast(request):
    if request.method == 'GET':
        recipe = Recipe.objects.order_by('-title')
        data = {
            'recipe': recipe
        }
        return render(request, 'main/breakfast.html', data)


def lunch(request):
    if request.method == 'GET':
        recipe = Recipe.objects.order_by('-title')
        data = {
            'recipe': recipe
        }
        return render(request, 'main/obedy.html', data)


def recipes_launch(request):
    error = ''
    form = RecipeForm()

    if request.method == "GET":
        form = RecipeForm(request.GET)
        data = {
            'form': form
        }
        return render(request, 'main/recipes_launch.html', data)

    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            return redirect('/')
        else:
            error = 'Форма была неверно заполнена'

    data = {
        'form': form,
        'error': error

    }
    return render(request, 'main/recipes_launch.html', data)


def recept1(request):
    return render(request, 'main/Recept1.html')


# Ненужное
#
# def registration(request):
#     return render(request, 'main/registration.html')
#
#
# def signin(request):
#     return render(request, 'main/signin.html')


def dinner(request):
    if request.method == 'GET':
        recipe = Recipe.objects.order_by('-title')
        data = {
            'recipe': recipe
        }
    return render(request, 'main/dinner.html', data)


def dessert(request):
    if request.method == 'GET':
        recipe = Recipe.objects.order_by('-title')
        data = {
            'recipe': recipe
        }
        return render(request, 'main/dessert.html', data)


def drink(request):
    if request.method == 'GET':
        recipe = Recipe.objects.order_by('-title')
        data = {
            'recipe': recipe
        }
        return render(request, 'main/drink.html', data)


def favorite_recipe(request, recipe_id):
    if request.method == "POST":
        recipe = get_object_or_404(Recipe, pk=recipe_id)
        if not recipe.favorite.filter(id=request.user.id).exists():
            recipe.favorite.add(request.user)
            recipe.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            recipe.favorite.remove(request.user)
            recipe.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def user_favorite(request):
    user = request.user
    recipes = Recipe.objects.filter(favorite__in=[user])

    context = {'user': user, "recipes": recipes}
    return render(request, "main/favorites.html", context)


class RecipeId(DetailView):
    model = Recipe
    template_name = 'main/recipe_id.html'
    context_object_name = 'Recipe'


def profile1(request):
    if request.method == 'GET':
        recipe = Recipe.objects.filter(user=request.user).order_by('-title')
        data = {
            'recipe': recipe,
        }
        return render(request, 'main/profile1.html', data)

book_recipe/main/templates/main/comming-soon.html
<!DOCTYPE html>
<html lang="zxx" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="assets/images/logo/favicon.ico" rel="icon">
    <title>Cafe360 - landing page</title>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/animate.css" type="text/css">
    <link rel="stylesheet" type="text/css" href="assets/css/fontawesome-all-min.css">
    <link rel="stylesheet" href="assets/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" type="text/css" href="assets/css/animate.css">
    <link rel="stylesheet" type="text/css" href="assets/css/style.css">
    <link rel="stylesheet" type="text/css" href="assets/css/media-query.css">
</head>

<body data-spy="scroll" data-target="#myHeader">

<!-- Preloader -->
<div class="preloader">
    <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 35.235 35.235" xml:space="preserve">
        <g>
            <g id="b103_soup">
                <path id="cap" d="M26.776,12.687H19.25c0.68,0,1.233-0.553,1.233-1.234s-0.554-1.23-1.233-1.23h-3.078c-0.68,0-1.232,0.549-1.232,1.23
                    s0.553,1.234,1.232,1.234H8.645c-2.094,0-3.828,1.877-4.165,3.875h26.464C30.605,14.563,28.871,12.687,26.776,12.687z"></path>
                <path id="body" d="M31.005,18.677v-0.352H4.479H4.417H0v1.762h4.417v10.918c0,2.338,1.894,4.229,4.228,4.229h18.132
                c2.336,0,4.229-1.891,4.229-4.229V20.439h4.229v-1.762H31.005z"></path>
                <path class="smell" id="elem-1" d="M11.24,4.235c0.123,0.162,0.254,0.318,0.391,0.465l0.341,0.342c0.216,0.217,0.417,0.434,0.577,0.629
                    c0.08,0.098,0.146,0.191,0.195,0.268c0.047,0.076,0.09,0.135,0.1,0.223c0.012,0.094-0.037,0.221-0.133,0.348
                    c-0.096,0.125-0.23,0.246-0.387,0.367c0.186,0.072,0.389,0.096,0.605,0.07c0.215-0.025,0.451-0.121,0.648-0.326
                    c0.195-0.205,0.304-0.508,0.321-0.775c0.019-0.27-0.022-0.514-0.083-0.734c-0.123-0.438-0.327-0.793-0.545-1.119
                    c-0.109-0.16-0.244-0.322-0.34-0.447c-0.096-0.113-0.185-0.229-0.266-0.344c-0.33-0.459-0.561-0.873-0.647-1.359
                    c-0.09-0.492,0.01-1.121,0.307-1.842c-0.771,0.162-1.457,0.807-1.681,1.709c-0.111,0.445-0.087,0.934,0.032,1.363
                    C10.793,3.511,11.002,3.897,11.24,4.235z"></path>
                <path class="smell" id="elem-2" d="M15.809,4.235C15.932,4.397,16.064,4.553,16.2,4.7l0.34,0.342c0.216,0.217,0.416,0.434,0.58,0.629
                    c0.077,0.098,0.143,0.191,0.193,0.268c0.049,0.076,0.09,0.135,0.098,0.223c0.013,0.094-0.035,0.221-0.131,0.348
                    c-0.095,0.125-0.23,0.246-0.389,0.367c0.188,0.072,0.392,0.096,0.607,0.07c0.214-0.025,0.453-0.121,0.648-0.326
                    c0.197-0.205,0.304-0.508,0.322-0.775c0.019-0.27-0.021-0.514-0.082-0.734c-0.125-0.438-0.33-0.793-0.548-1.119
                    c-0.107-0.16-0.243-0.322-0.339-0.447c-0.094-0.113-0.185-0.229-0.264-0.344c-0.331-0.459-0.563-0.873-0.649-1.359
                    c-0.09-0.49,0.008-1.119,0.304-1.84c-0.77,0.162-1.455,0.807-1.678,1.709c-0.111,0.445-0.088,0.934,0.031,1.363
                    C15.363,3.511,15.568,3.897,15.809,4.235z"></path>
                <path class="smell" id="elem-3" d="M19.972,4.235c0.122,0.162,0.253,0.318,0.39,0.465l0.341,0.342c0.216,0.217,0.415,0.434,0.577,0.629
                    c0.08,0.098,0.146,0.191,0.195,0.268c0.047,0.076,0.088,0.135,0.1,0.223c0.013,0.094-0.037,0.221-0.133,0.348
                    c-0.095,0.125-0.23,0.246-0.389,0.367c0.188,0.072,0.392,0.096,0.605,0.07c0.215-0.025,0.453-0.121,0.65-0.326
                    c0.195-0.205,0.303-0.508,0.32-0.775c0.02-0.27-0.021-0.514-0.082-0.734c-0.123-0.438-0.326-0.793-0.545-1.119
                    c-0.109-0.16-0.244-0.322-0.34-0.447c-0.096-0.113-0.186-0.229-0.266-0.344c-0.33-0.459-0.561-0.873-0.646-1.359
                    c-0.091-0.492,0.009-1.121,0.304-1.842c-0.77,0.162-1.457,0.807-1.679,1.709c-0.11,0.445-0.087,0.934,0.032,1.363
                    C19.524,3.511,19.731,3.897,19.972,4.235z"></path>
            </g>
            <g id="Capa_1_128_"></g>
        </g>
    </svg>
</div>
    
<!-- Page Wrapper -->
<div id="wrap">
    <section class="cm-page-content">
        <div class="container">
            <div class="cs-content-center">
                <div class="logo mb-4 cs-header">
                    <a href="index.html">
                        <img src="assets/images/logo/logo.png" class="img-fluid" alt="The cafe360 Logo Image">
                    </a>
                </div>
                <h1>New Restaurant Opening</h1>  
                 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p> 
                <div class="cs-counter" id="timelist">
                    <ul class="p-0">
                        <li>
                            <h2 class="days">20</h2>
                            <span>Days</span>
                        </li>
                        <li>
                            <h2 class="hours">09</h2>
                            <span>Hours</span>
                        </li>
                        <li>
                            <h2 class="minutes">59</h2>
                            <span>Minutes</span>
                        </li>
                        <li>
                            <h2 class="seconds">47</h2>
                            <span>Seconds</span>
                        </li>
                    </ul>
                </div>
                <div class="cs-footer">
                    <div class="footer-copylink text-center">
                        <span>© Design by <a target="_blank" href="https://themeforest.net/user/the_krishna">The_Krishna</a></span>
                    </div>
                    <div class="col-md-12 cs-footer-icon text-center">
                          <a class="fb-ic" href="javascript:void(0);">
                            <i class="fab fa-facebook-f wow fadeInDown" data-wow-duration="1.5s" data-wow-delay=".4s"> </i>
                          </a>
                          <a class="tw-ic"  href="javascript:void(0);">
                            <i class="fab fa-twitter wow fadeInUp" data-wow-duration="1.5s" data-wow-delay=".4s"> </i>
                          </a>
                          <a class="ins-ic"  href="javascript:void(0);">
                            <i class="fab fa-instagram wow fadeInDown" data-wow-duration="1.5s" data-wow-delay=".4s"> </i>
                          </a>
                          <a class="pin-ic"  href="javascript:void(0);">
                            <i class="fab fa-pinterest wow fadeInUp" data-wow-duration="1.5s" data-wow-delay=".4s"> </i>
                          </a>
                          <a class="sn-ic"  href="javascript:void(0);">
                            <i class="fab fa-snapchat wow fadeInDown" data-wow-duration="1.5s" data-wow-delay=".4s"> </i>
                          </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<!-- Page Wrapper -->
   
<script src="assets/js/jquery-3.5.1.slim.min.js"></script>
<script src="assets/js/bootstrap.bundle.min.js"></script>
<script src="assets/js/wow.min.js"></script>
<script src="assets/js/comming-soon.js"></script>
<script src="assets/js/ajax-jquery.min.js"></script>
<script>
    new WOW().init();
</script>
</body>

</html>

book_recipe/main/templates/main/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Добавление рецептов</title>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/media-query.css' %}">
    <!--<link rel="stylesheet" href="{%static 'css/lanch.css' %}">-->
    <link rel="stylesheet" href="{%static 'css/recipes_launch.css' %}">
</head>
<body>


    <div id="wrap">

        <!-- start slider section -->
        <!--<section class="home-slider">-->
        <div class="container1">
            <h2 id="tu">Редактирование рецептов</h2>
                       <div class="recipes_launch">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.title }}<br>
                                {{ form.ingredients }}<br>
                                {{ form.steps }} <br>
<!--<textarea name="steps" cols="40" rows="10" class="form-control" placeholder="Шаги приготовления" required="" id="id_steps" style="
    height: 153.6px;
"></textarea>-->
                                <br>
                                <h6>кКал</h6>{{form.calories}}<br>
                                <h6>{{form.online}} Опубликовать</h6>
<select name="category" id="id_category" >
  <option value="---">---</option>

  <option value="breakfast">Завтрак</option>

  <option value="lunch">Обед</option>

  <option value="dinner">Ужин</option>

  <option value="dessert">Десерт</option>

  <option value="drink">Напиток</option>

</select>


                                <p>Выбрать фотографию блюда</p>
                                {{form.image}}


<!--&lt;!&ndash;                                <p><input type="file" name="photo" multiple accept="image/*,image/jpeg">&ndash;&gt;-->
<!--                                <button class="btn btn-success" type="submit">Добавить рецепт</button>-->
                            <button class="button-1"  type="submit">Изменить рецепт</button>
                            </form>
                            <form action="/.." target="">
                                <button class="button-2">На главную</button>
                            </form>
                                <!--<button class="button-1"  type="submit" >На главную</button>-->
                        </div>
                    </div>
                </div>
            </div>
            </div>
        <!--</section>-->
    <!-- END slider section -->


    </div>

<footer class="position-relative wow fadeIn" data-wow-duration="2s" data-wow-delay=".4s">
    <div class="footer-bottom" style="top: 0px;">
        <div class="container position-relative">
            <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="footer-menu text-center">
<!--                        <ul>-->
<!--                            <li class="nav-item"><a class="nav-link" href="Завтраки">Завтраки</a>-->
<!--                            </li>-->
<!--                            <li class="nav-item"><a class="nav-link" href="Обеды">Обеды</a>-->
<!--                            </li>-->
<!--                            <li class="nav-item"><a class="nav-link" href="Ужины">Ужины</a>-->
<!--                            </li>-->
<!--                            <li class="nav-item"><a class="nav-link" href="Десерты">Десерты</a>-->
<!--                            </li>-->
<!--                            <li class="nav-item"><a class="nav-link" href="Напитки">Напитки</a>-->
<!--                            </li>-->
<!--                            <li class="nav-item"><a class="nav-link" href="Избранное">Избранное</a>-->
<!--                            </li>-->
<!--                        </ul>-->
                    </div>
                 </div>
            </div>
            <div class="row">
                <div class="col-12 col-md-12 col-lg-12 text-center">
                    <div class="footer-logo">
                        <img src="{% static 'assets/images/footer-images/dsadadsdad.png' %}" alt="the logo image | Footer cafe Logo" >
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>




</body>
</html>

book_recipe/main/templates/main/recipes.html
<!DOCTYPE html>
<html lang="en">
<head>
    {%load static%}

    <link rel="stylesheet" href="{%static 'css/recipes.css' %}">


    <meta charset="UTF-8">
    <title>Title</title>
    <style>
<!--        .body{-->
<!--          display: flex;-->
<!--          justify-content: center;-->
<!--          align-items: center;-->
<!--          height: 100%;-->
<!--        }-->


<!--        .container{-->
<!--            display: grid;-->
<!--            grid-template-columns: repeat(3, 1fr);-->
<!--            grid-auto-rows: 100px;-->
<!--            width: 90vw;-->
<!--            height: 80vh;-->
<!--            background: grey;-->
<!--            margin: 0 auto;-->
<!--        }-->

<!--        .item {-->
<!--            display: grid;-->
<!--            border: 1px solid black;-->
<!--            background: white;-->
<!--            margin: 0 auto;-->
<!--            margin-top: 100px;-->
<!--            width: 250px;-->
<!--            height: 300px;-->
<!--            grid-template-rows: 130px 1fr;-->
<!--        }-->

<!--        .image{-->
<!--            display: grid;-->

<!--            border: 1px solid black;-->


<!--        }-->
<!--        .text{-->
<!--            display: grid;-->

<!--            border: 1px solid black;-->

<!--        }-->



    </style>
</head>
<body>
    <div class="container">

        <div class="item item1">
            <div class="image">img</div>
            <div class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, architecto, asperiores atque culpa dolore eligendi error impedit laborum laudantium nobis repellendus reprehenderit suscipit tempora unde voluptate. Consequatur explicabo magni perferendis.</div>
        </div>

        <div class="item item2">
            <div class="image">img</div>
            <div class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, architecto, asperiores atque culpa dolore eligendi error impedit laborum laudantium nobis repellendus reprehenderit suscipit tempora unde voluptate. Consequatur explicabo magni perferendis.</div>
        </div>

        <div class="item item3">
            <div class="image">img</div>
            <div class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, architecto, asperiores atque culpa dolore eligendi error impedit laborum laudantium nobis repellendus reprehenderit suscipit tempora unde voluptate. Consequatur explicabo magni perferendis.</div>
        </div>

    </div>
</body>
</html>

book_recipe/main/templates/main/recipes_launch.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Добавление рецептов</title>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/media-query.css' %}">
    <!--<link rel="stylesheet" href="{%static 'css/lanch.css' %}">-->
    <link rel="stylesheet" href="{%static 'css/recipes_launch.css' %}">
</head>
<body>


    <div id="wrap">

        <!-- start slider section -->
        <!--<section class="home-slider">-->
        <div class="container1">
            <h2 id="tu">Добавление рецептов</h2>
                       <div class="recipes_launch">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.title }}<br>
                                {{ form.ingredients }}<br>

<textarea name="steps" cols="40" rows="10" class="form-control" placeholder="Шаги приготовления" required="" id="id_steps" style="
    height: 153.6px;
"></textarea>
                                <br>
                                <h6>кКал</h6>{{form.calories}}<br>
                                {{form.time_cooking}}<br>

<select name="category" id="id_category" >
  <option value="---">---</option>

  <option value="breakfast">Завтрак</option>

  <option value="lunch">Обед</option>

  <option value="dinner">Ужин</option>

  <option value="dessert">Десерт</option>

  <option value="drink">Напиток</option>

</select>


                                <p>Выбрать фотографию блюда</p>
                                {{form.image}}


<!--&lt;!&ndash;                                <p><input type="file" name="photo" multiple accept="image/*,image/jpeg">&ndash;&gt;-->
<!--                                <button class="btn btn-success" type="submit">Добавить рецепт</button>-->
                            <button class="button-1"  type="submit">Добавить рецепт</button>
                            </form>
                            <form action="/.." target="">
                                <button class="button-2">На главную</button>
                            </form>
                                <!--<button class="button-1"  type="submit" >На главную</button>-->
                        </div>
                    </div>
                </div>
            </div>
            </div>
        <!--</section>-->
    <!-- END slider section -->


    </div>

<footer class="position-relative wow fadeIn" data-wow-duration="2s" data-wow-delay=".4s">
    <div class="footer-bottom" style="top: 0px;">
        <div class="container position-relative">
            <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="footer-menu text-center">
<!--                        <ul>-->
<!--                            <li class="nav-item"><a class="nav-link" href="Завтраки">Завтраки</a>-->
<!--                            </li>-->
<!--                            <li class="nav-item"><a class="nav-link" href="Обеды">Обеды</a>-->
<!--                            </li>-->
<!--                            <li class="nav-item"><a class="nav-link" href="Ужины">Ужины</a>-->
<!--                            </li>-->
<!--                            <li class="nav-item"><a class="nav-link" href="Десерты">Десерты</a>-->
<!--                            </li>-->
<!--                            <li class="nav-item"><a class="nav-link" href="Напитки">Напитки</a>-->
<!--                            </li>-->
<!--                            <li class="nav-item"><a class="nav-link" href="Избранное">Избранное</a>-->
<!--                            </li>-->
<!--                        </ul>-->
                    </div>
                 </div>
            </div>
            <div class="row">
                <div class="col-12 col-md-12 col-lg-12 text-center">
                    <div class="footer-logo">
                        <img src="{% static 'assets/images/footer-images/dsadadsdad.png' %}" alt="the logo image | Footer cafe Logo" >
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>




</body>
</html>

book_recipe/main/templates/main/signIn.html
<!DOCTYPE html>
<html lang="zxx" dir="ltr">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Вход</title>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/registr.css' %}">
</head>

<body>
    <div class="container">
    <h2 id="sign">Войти в аккаунт</h2>
    <form action="registration.php" method="POST">
      <div class="form-group">
        <label for="name">Имя:</label>
        <input type="text" id="name" name="name" required>
      </div>
      <div class="form-group">
        <label for="password">Пароль:</label>
        <input type="password" id="password" name="password" required>
      </div>
      <div class="form-group">
        <button type="submit" class="button-1">Вход</button>
      </div>
    </form>
        <form action="http://127.0.0.1:8000" target="">
            <button class="button-2">На главную</button>
        </form>
    </div>
</body>

</html>